### ISSUE TITLE
スマホ対応　レスポンシブ？

### ISSUE THREAD

**Issue by h-mizo** [m-kodama/app-odai-gacha#8]
### 現状
最大画面にしか対応していないのわろたwww
位置をcssでどうにかするかな

### やり方
画像二つでやってるからだるそう
％で調節じゃずれた…

**Comment by m-kodama** [comment]
腕の位置、これでいけいないかな？
211行目 `handle.style.right = gacha.clientWidth * 0.32 + 'px'`

**Comment by m-kodama** [comment]
### スマホ対応 TODO

- [ ] 画像の位置をパーセンテージ等で指定して、どんな画面サイズでも正しく表示する
- [ ]  現状はマウスイベント（mousedown等）しか対応していないが、タッチイベント（touchstart等）に変更してタッチ対応する

**Comment by h-mizo** [comment]
> 腕の位置、これでいけいないかな？
だいぶずれたw　胴長的な

**Comment by h-mizo** [comment]
> 腕の位置、これでいけいないかな？

0.40がべすと

**Comment by h-mizo** [comment]
おわりました　（スマホはまだあとでね）
